---
params:
  lesson: "Conversation connectors"
  title: Useful conversation connectors    
  link: "https://traverse.link/Mandarin_Blueprint/lri7y3w5cikbvl1pd3a37kbm"
  content: ""  
  date: !r Sys.Date()
  email: matthew.malishev@gmail.com    
  # end inputs ---------------------------------------------------------------
header-includes: \usepackage{float}
always_allow_html: yes
output:
  html_document 
---

```{r echo = FALSE}
# library(rmarkdown)
# setwd("")
# f <- list.files()[1]
# render(f, output_format='pdf_document')
```

```{r, set-options, echo = FALSE, cache = FALSE}
options(width=100)
knitr::opts_chunk$set(
 eval = TRUE, # run all code
 # echo = FALSE, # show code chunks in output 
 comment = "",
 tidy.opts=list(width.cutoff=100), # set width of code chunks in output
 tidy=TRUE, # make output as tidy
 message = FALSE,  # mask all messages
 warning = FALSE, # mask all warnings 
 size="small" # set code chunk size
)

# https://github.com/ucb-stat133/stat133-fall-2016/blob/master/hws/hw02-tables-ggplot.Rmd
knitr::opts_knit$set(root.dir=paste0(params$dir,"/")) # set working dir

setwd(paste0(params$dir,"/")) # for running just in R not knitr
```

\  

\  

\  

\  

# `r paste0(params$lesson,": ",params$title)`      
## `r params$content`        
\  

<!-- ____________________________________________________________________________ -->
<!-- ____________________________________________________________________________ -->
<!-- ____________________________________________________________________________ -->
<!-- start body -->  
  
## Commonly used conversation connectors and prepositions      

General    
```{r, echo = F, eval = T, warning=F}
# what,where,who etc examples converted to html table 
library(knitr)
library(dplyr)
library(readr)

# Input text
txt <- "/Users/malishev/Documents/chinese/mooc/chinese_mooc/connectors_general.txt" %>%
  read_lines() %>% 
  stringr::str_trim(side = "both") %>% 
  matrix(ncol = 4, byrow = T) %>% 
  as.data.frame %>% 
  setNames(c("English", "Mandarin", "Translation","")) %>% # add extra col for para break in txt file  
  kable() 
txt
```

******   
\    

Memory/thought/opinion     
```{r, echo = F, eval = T, warning=F}
# what,where,who etc examples converted to html table 
library(knitr)
library(dplyr)
library(readr)

# Input text
txt <- "/Users/malishev/Documents/chinese/mooc/chinese_mooc/connectors_opinion.txt" %>%
  read_lines() %>% 
  stringr::str_trim(side = "both") %>% 
  matrix(ncol = 4, byrow = T) %>% 
  as.data.frame %>% 
  setNames(c("English", "Mandarin", "Translation","")) %>% # add extra col for para break in txt file  
  kable() 
txt
```


******   
\  

Talk/speak/word-related   
```{r, echo = F, eval = T, warning=F}
# what,where,who etc examples converted to html table 
library(knitr)
library(dplyr)
library(readr)

# Input text
txt <- "/Users/malishev/Documents/chinese/mooc/chinese_mooc/connectors_talk.txt" %>%
  read_lines() %>% 
  stringr::str_trim(side = "both") %>% 
  matrix(ncol = 4, byrow = T) %>% 
  as.data.frame %>% 
  setNames(c("English", "Mandarin", "Translation","")) %>% # add extra col for para break in txt file  
  kable() 
txt
```


******   
\  






