---
params:
  lesson: "Questions for Yu"  
  title: ""          
  link: "https://moocs.unipus.cn/course/373/task/27612/show"
  content: ""  
  date: !r Sys.Date()
  email: matthew.malishev@gmail.com    
  # end inputs ---------------------------------------------------------------
header-includes: \usepackage{float}
always_allow_html: yes
output:
  html_document 
---

\  

\  

\  

\  


## Questions for 鱼老师      

两 vs 辆     
你 vs 您  

******  

## Lesson 2.3  
how is '着' used correctly here?  
他最喜欢喝着啤酒看足球比赛。     

******  

## Lesson 2.5  
张 or 个？  
这是一张中国拍的照片。     

Why is this correct?  
安妮 是  我们  班  汉 语  说   得 最  好  的 学 生。       
MISTAKE IN COURSE. SHOULD BE DOUBLE VERB WITH 得.  

******  

## Lesson 3.1    
Why is the top one not correct like the bottom one?   
这件衣服跟那件衣服一样颜色。   
这件衣服的颜色跟那件衣服一样。 
红 needs to be an adjective, not a noun   
  
******    
  
## Lesson 3.2   

Should the top one be the bottom instead?  
爸爸比妈妈很忙 (incorrect)        
爸爸比妈妈更忙 (correct)?         
Top one is 'very busy', which doesn't work when comparing subjects     

******  

## Lesson 3.3  
这个对马？   
一班比二班多五个学生了。   
Correct  


******  

******    

## Lesson 5.1  

Why does 要花 = spend? Seperately they mean 'want' and 'flower'.    

\  

How do we use '到。。。以后，。。。' properly?  
The example given is 到宾馆以后
Are these correct?  
到电影以后，。。。  
到上课以后， 。。。  

\  

******  

## Lesson 5.2  

How does 遍 translate? My understanding is it doesn't mean 'again', but instead means 'from start to finish'.  

\   

What's the translation of 到过？  
e.g.  
这本书我在书店看到过几次。  

******  

## Lesson 5.3   

Why is 给 necessary here when 拿来了 means the same thing?    
他给我拿来了一杯咖啡。     

Are these options correct?  
他给我一杯咖啡    
vs.     
他拿来了一杯咖啡      

\  

Why is this correct (过来)?    
你看！车站在马路那边，你快过来吧。  

\  

******  

## Lesson 5.5     

Are these sentences essentially the same thing?    
他们能不能吃完？    
他们能吃完样？      

Why is this correct? Shouldn't the part before 不 be a verb， e.g. 。。。我去不上?      
地铁 里的人 太 多 了，我上不去。      

\  

******  

## Lesson 6.1       

Why is this incorrect?      
姐姐把一个苹果洗干净了。

\  

******  

## Lesson 6.3         

Are these all the same and correct?  
我没把花送给你。     
我没把花给你。     
我没花送给你。   
我没花给你。     

******    

### Lesson 7.4  

不知道。 谁也没见过他。    
What does 谁也 translate to here?    

## General   

There seems to be a lot of ways to say 'everyone'. When do you use the following?  

每个人 （every person)?    
大家  (everyone)?  
所有  (all)?  

What does '司' mean? It's found in 公司， but has the radical 口 in it 。         


