---
params:
  lesson: "Lesson 2"   
title: "Mandarin X Intermediate Chinese"        
link: "https://moocs.unipus.cn/course/373/task/27612/show"
content: "Intro and vocab"  
email: matthew.malishev@gmail.com      
# end inputs ---------------------------------------------------------------
header-includes: \usepackage{float}
always_allow_html: yes
output:
  html_document
---
  
  ```{r echo = FALSE}
# library(rmarkdown)
# setwd("")
# f <- list.files()[1]
# render(f, output_format='pdf_document')
```

```{r, set-options, echo = FALSE, cache = FALSE}
options(width=100)
knitr::opts_chunk$set(
  eval = TRUE, # run all code
  # echo = FALSE, # show code chunks in output 
  comment = "",
  tidy.opts=list(width.cutoff=100), # set width of code chunks in output
  tidy=TRUE, # make output as tidy
  message = FALSE,  # mask all messages
  warning = FALSE, # mask all warnings 
  size="small" # set code chunk size
)

# https://github.com/ucb-stat133/stat133-fall-2016/blob/master/hws/hw02-tables-ggplot.Rmd
knitr::opts_knit$set(root.dir=paste0(params$dir,"/")) # set working dir

setwd(paste0(params$dir,"/")) # for running just in R not knitr
```

\  

\  

\  

\  


# `r paste0(params$lesson,": ",params$title)`    
\  

Content for `r params$lesson`  
`r params$content`      
\  

<!-- ____________________________________________________________________________ -->
  <!-- ____________________________________________________________________________ -->
  <!-- ____________________________________________________________________________ -->
  <!-- start body -->  
  
## `r params$title`      
  
特别 special    
她特别高 She is exceptionally tall     

酷 cool  
她很酷  He's very cool  

价钱 price  


  